
title: Remind me
email: alexandre.ravichandran@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Vous avez toujours revé 
domain: "remind-me.github.io" 
url: "https://remind-me.github.io"
github_username:  AlexandreRavichandran

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
